[package]
name = "jup"
authors = ["Junon", "Antonin Hérault <antonherault@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
rslog = { git = "https://github.com/antoninhrlt/rslog" }
x64asm = "*"
